// <auto-generated />
using System;
using CHG_Legal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CHG_Legal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515093057_FinalAttachmentServiceFix")]
    partial class FinalAttachmentServiceFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CHG_Legal.Models.Entities.Approval", b =>
                {
                    b.Property<int>("ApprovalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ApprovalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalID"));

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ApprovedBy");

                    b.Property<int>("Attendee_ID")
                        .HasColumnType("int")
                        .HasColumnName("Attendee_ID");

                    b.Property<int>("BoardApprovalID")
                        .HasColumnType("int")
                        .HasColumnName("BoardApprovalID");

                    b.HasKey("ApprovalID");

                    b.HasIndex("Attendee_ID");

                    b.HasIndex("BoardApprovalID");

                    b.ToTable("Approves");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.Association", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AssociationType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double?>("ValidityValue")
                        .HasColumnType("float");

                    b.Property<string>("VotingMechanism")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID");

                    b.ToTable("Association");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.AssociationPlace", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AsscoiationPlace")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("associationID")
                        .HasColumnType("int");

                    b.Property<string>("associationPlaceDecr")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.HasKey("ID");

                    b.HasIndex("associationID");

                    b.ToTable("AssociationPlace");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.Attendee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("JobDescription")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("Job_Describtion");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Attendee");

                    b.HasKey("ID");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BankingAttachment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BankingGroupGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("MemberName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("file_data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("file_path")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("file_size")
                        .HasColumnType("bigint");

                    b.Property<string>("file_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("mime_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("uploaded_at")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("BankingGroupGroupId");

                    b.HasIndex("CompanyId");

                    b.ToTable("BankingAttachments", "Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BankingGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("GroupId");

                    b.HasIndex("CompanyId");

                    b.ToTable("BankingGroups", "Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BankingGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("MemberName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("BankingGroupMembers", "Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.Board", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Attendees")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)")
                        .HasColumnName("Attendees");

                    b.Property<DateTime>("BoardDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("BoardDate");

                    b.Property<string>("BoardDecisionsText")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)")
                        .HasColumnName("BoardDescsions");

                    b.Property<int>("BoardTypeID")
                        .HasColumnType("int")
                        .HasColumnName("BoardTypeID");

                    b.Property<string>("CHGParty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CHGParty");

                    b.Property<string>("MeetingStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MeetingStatus");

                    b.Property<string>("MeetingType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MeetingType");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Notes");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Subject");

                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ID");

                    b.HasIndex("BoardTypeID");

                    b.HasIndex("UserID");

                    b.ToTable("Board");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BoardAttachment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Board_id")
                        .HasColumnType("int")
                        .HasColumnName("Board_id");

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<byte[]>("file_data")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("file_data");

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("file_path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_path");

                    b.Property<long?>("file_size")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("file_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("file_type");

                    b.Property<string>("mime_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("mime_type");

                    b.Property<DateTime>("uploaded_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.Property<int>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ID");

                    b.HasIndex("Board_id");

                    b.HasIndex("user_id");

                    b.ToTable("Board_Attachments");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BoardAttendee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ApprovedBy");

                    b.Property<int>("Attendee_ID")
                        .HasColumnType("int")
                        .HasColumnName("Attendee_ID");

                    b.Property<int>("BoardID")
                        .HasColumnType("int")
                        .HasColumnName("BoardID");

                    b.HasKey("ID");

                    b.HasIndex("Attendee_ID");

                    b.HasIndex("BoardID");

                    b.ToTable("BoardAttendees");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BoardDecision", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Board_ID")
                        .HasColumnType("int")
                        .HasColumnName("Board_ID");

                    b.Property<DateTime>("DateInserted")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateInserted");

                    b.Property<string>("Decision_Details")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)")
                        .HasColumnName("Decesion_Details");

                    b.Property<short>("Decision_Number")
                        .HasColumnType("smallint")
                        .HasColumnName("Decesion_Number");

                    b.Property<string>("IsExecuted")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IsExcuted");

                    b.Property<string>("Notes")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)")
                        .HasColumnName("Notes");

                    b.HasKey("ID");

                    b.HasIndex("Board_ID");

                    b.ToTable("BoardDecisions");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BoardMember", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<int?>("BoardId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Position")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MemberId");

                    b.HasIndex("BoardId");

                    b.ToTable("BoardMembers", "Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BoardMemberAttach", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BoardSettingBoardId")
                        .HasColumnType("int");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("file_data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("file_path")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("file_size")
                        .HasColumnType("bigint");

                    b.Property<string>("file_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("mime_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("uploaded_at")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("BoardSettingBoardId");

                    b.HasIndex("MemberId");

                    b.ToTable("BoardMemberAttaches", "Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BoardSetting", b =>
                {
                    b.Property<int>("BoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoardId"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NotificationPeriod")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BoardId");

                    b.HasIndex("CompanyId");

                    b.ToTable("BoardSettings", "Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BoardType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BoardTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("BoardType");

                    b.HasKey("ID");

                    b.ToTable("BoardType");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RegistrationNotification")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BranchId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Branches", "Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BranchAttachment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("file_data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("file_path")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("file_size")
                        .HasColumnType("bigint");

                    b.Property<string>("file_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("mime_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("uploaded_at")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("BranchId");

                    b.HasIndex("CompanyId");

                    b.ToTable("BranchAttachments", "Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("AccountingAuditor")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("AccountingAuditorHiringDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("AuthorizedCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AuthorizedCapitalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CardRenewalDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CardRenewalDue")
                        .HasColumnType("int");

                    b.Property<string>("CommercialRegNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HeadOfficeAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("IssuedCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("IssuedCapitalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("PaidUpCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaidUpCapitalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RegistrationExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RegistrationNotificationPeriod")
                        .HasColumnType("int");

                    b.Property<string>("TaxCardNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("VAT")
                        .HasColumnType("float");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies", "Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.CompanyAttachment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("file_data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("file_path")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("file_size")
                        .HasColumnType("bigint");

                    b.Property<string>("file_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("mime_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("uploaded_at")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyAttachments", "Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.Group", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GroupName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID");

                    b.ToTable("Groups", "Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.Hospital", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Hospital");

                    b.HasKey("ID");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.HospitalAttendee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Attendee_ID")
                        .HasColumnType("int")
                        .HasColumnName("Attendee_ID");

                    b.Property<int>("Hospital_ID")
                        .HasColumnType("int")
                        .HasColumnName("Hospital_ID");

                    b.HasKey("ID");

                    b.HasIndex("Attendee_ID");

                    b.HasIndex("Hospital_ID");

                    b.ToTable("Hospital_Attendees");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.NonBankingAttach", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AuthorizationId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("file_data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("file_path")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("file_size")
                        .HasColumnType("bigint");

                    b.Property<string>("file_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("mime_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("uploaded_at")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("CompanyId");

                    b.ToTable("NonBankingAttaches", "Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.NonBankingAuthorization", b =>
                {
                    b.Property<int>("AuthorizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorizationId"));

                    b.Property<string>("AuthorizationDetails")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuedTo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("NotificationPerid")
                        .HasColumnType("int");

                    b.HasKey("AuthorizationId");

                    b.HasIndex("CompanyId");

                    b.ToTable("NonBankingAuthorizations", "Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RoleName");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.ShareHolder_Attaches", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("ShareholderId")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("file_data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("file_path")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("file_size")
                        .HasColumnType("bigint");

                    b.Property<string>("file_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("mime_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("uploaded_at")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ShareholderId");

                    b.ToTable("ShareHolder_Attaches", "dbo");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.ShareValue", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double?>("Value")
                        .HasColumnType("float")
                        .HasColumnName("ShareValue");

                    b.HasKey("ID");

                    b.ToTable("ShareValue");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.Shareholder", b =>
                {
                    b.Property<int>("ShareholderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShareholderId"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("ExcellentShareCount")
                        .HasColumnType("float");

                    b.Property<string>("FounderName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("FounderShareCount")
                        .HasColumnType("float");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShareName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SharesPercentage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("SubscribedShareCount")
                        .HasColumnType("float");

                    b.Property<double?>("TotalShareCounts")
                        .HasColumnType("float");

                    b.HasKey("ShareholderId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Shareholders", "Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.User", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("Active");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("Password");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("User_Name");

                    b.HasKey("User_ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("RoleID")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.Approval", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.Attendee", "Attendee")
                        .WithMany("Approvals")
                        .HasForeignKey("Attendee_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CHG_Legal.Models.Entities.Board", "Board")
                        .WithMany("Approvals")
                        .HasForeignKey("BoardApprovalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendee");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.AssociationPlace", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.Association", "Association")
                        .WithMany("AssociationPlaces")
                        .HasForeignKey("associationID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Association");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BankingAttachment", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.BankingGroup", null)
                        .WithMany("BankingAttachments")
                        .HasForeignKey("BankingGroupGroupId");

                    b.HasOne("CHG_Legal.Models.Entities.Company", "Company")
                        .WithMany("BankingAttachments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BankingGroup", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.Company", "Company")
                        .WithMany("BankingGroups")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BankingGroupMember", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.BankingGroup", "BankingGroup")
                        .WithMany("BankingGroupMembers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BankingGroup");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.Board", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.BoardType", "BoardType")
                        .WithMany("Boards")
                        .HasForeignKey("BoardTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CHG_Legal.Models.Entities.User", "User")
                        .WithMany("Boards")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BoardAttachment", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.Board", "Board")
                        .WithMany("BoardAttachments")
                        .HasForeignKey("Board_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CHG_Legal.Models.Entities.User", "User")
                        .WithMany("BoardAttachments")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BoardAttendee", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.Attendee", "Attendee")
                        .WithMany("BoardAttendees")
                        .HasForeignKey("Attendee_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CHG_Legal.Models.Entities.Board", "Board")
                        .WithMany("BoardAttendees")
                        .HasForeignKey("BoardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendee");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BoardDecision", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.Board", "Board")
                        .WithMany("BoardDecisions")
                        .HasForeignKey("Board_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BoardMember", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.BoardSetting", "BoardSetting")
                        .WithMany("BoardMembers")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BoardSetting");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BoardMemberAttach", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.BoardSetting", null)
                        .WithMany("BoardMemberAttachments")
                        .HasForeignKey("BoardSettingBoardId");

                    b.HasOne("CHG_Legal.Models.Entities.BoardMember", "BoardMember")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BoardMember");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BoardSetting", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.Company", "Company")
                        .WithMany("BoardSettings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.Branch", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.Company", "Company")
                        .WithMany("Branches")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BranchAttachment", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.Branch", "Branch")
                        .WithMany("BranchAttachments")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CHG_Legal.Models.Entities.Company", "Company")
                        .WithMany("BranchAttachments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Branch");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.CompanyAttachment", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.Company", "Company")
                        .WithMany("CompanyAttachments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.HospitalAttendee", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.Attendee", "Attendee")
                        .WithMany("HospitalAttendees")
                        .HasForeignKey("Attendee_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CHG_Legal.Models.Entities.Hospital", "Hospital")
                        .WithMany("HospitalAttendees")
                        .HasForeignKey("Hospital_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendee");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.NonBankingAttach", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.NonBankingAuthorization", "NonBankingAuthorization")
                        .WithMany("NonBankingAttachments")
                        .HasForeignKey("AuthorizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CHG_Legal.Models.Entities.Company", "Company")
                        .WithMany("NonBankingAttachments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");

                    b.Navigation("NonBankingAuthorization");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.NonBankingAuthorization", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.Company", "Company")
                        .WithMany("NonBankingAuthorizations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.ShareHolder_Attaches", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CHG_Legal.Models.Entities.Shareholder", "Shareholder")
                        .WithMany()
                        .HasForeignKey("ShareholderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Shareholder");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.Shareholder", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.Company", "Company")
                        .WithMany("Shareholders")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("CHG_Legal.Models.Entities.Role", "Role")
                        .WithMany("UserRole")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CHG_Legal.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.Association", b =>
                {
                    b.Navigation("AssociationPlaces");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.Attendee", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("BoardAttendees");

                    b.Navigation("HospitalAttendees");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BankingGroup", b =>
                {
                    b.Navigation("BankingAttachments");

                    b.Navigation("BankingGroupMembers");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.Board", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("BoardAttachments");

                    b.Navigation("BoardAttendees");

                    b.Navigation("BoardDecisions");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BoardSetting", b =>
                {
                    b.Navigation("BoardMemberAttachments");

                    b.Navigation("BoardMembers");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.BoardType", b =>
                {
                    b.Navigation("Boards");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.Branch", b =>
                {
                    b.Navigation("BranchAttachments");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.Company", b =>
                {
                    b.Navigation("BankingAttachments");

                    b.Navigation("BankingGroups");

                    b.Navigation("BoardSettings");

                    b.Navigation("BranchAttachments");

                    b.Navigation("Branches");

                    b.Navigation("CompanyAttachments");

                    b.Navigation("NonBankingAttachments");

                    b.Navigation("NonBankingAuthorizations");

                    b.Navigation("Shareholders");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.Hospital", b =>
                {
                    b.Navigation("HospitalAttendees");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.NonBankingAuthorization", b =>
                {
                    b.Navigation("NonBankingAttachments");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.Role", b =>
                {
                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("CHG_Legal.Models.Entities.User", b =>
                {
                    b.Navigation("BoardAttachments");

                    b.Navigation("Boards");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
